common: &common
  adapter: postgresql
  username: _postgres
  password:
  host: localhost
  timeout: 5000

development:
  <<: *common
  database: simplewiki_dev

test: &test
  <<: *common
  database: simplewiki_test
