common: &common
  adapter: mysql2
  host: localhost
  port: 3306
  username: root
  password:

development:
  <<: *common
  database: simplewiki_dev

test: &test
  <<: *common
  database: simplewiki_test

cucumber:
  <<: *test
